services:
  app:
    build: .
    container_name: obs_app
    env_file:
      - ./env/app.env
    environment:
      APP_LOG_FILE: /app/logs/app.log
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - app_logs:/app/logs
    networks:
      - obs_net

  db:
    image: postgres:16-alpine
    container_name: obs_db
    env_file:
      - ./env/db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - obs_net

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: obs_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - obs_net

  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: obs_node_exporter
    ports:
      - "9100:9100"
    command:
      - "--path.rootfs=/host"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)"
    volumes:
      - /:/host:ro
    networks:
      - obs_net

  loki:
    image: grafana/loki:3.2.0
    container_name: obs_loki
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml:ro
    networks:
      - obs_net

  promtail:
    image: grafana/promtail:3.2.0
    container_name: obs_promtail
    command: ["-config.file=/etc/promtail/config.yml"]
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml:ro
      - app_logs:/var/log/app:ro
    depends_on:
      - loki
      - app
    networks:
      - obs_net

  grafana:
    image: grafana/grafana:11.2.0
    container_name: obs_grafana
    env_file:
      - ./env/grafana.env
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
      - loki
    networks:
      - obs_net

volumes:
  pg_data:
  grafana_data:
  app_logs:

networks:
  obs_net:
    driver: bridge
